# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-06 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articls', '0004_articleslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleslider',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
